# Generated by Django 4.1.3 on 2022-11-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('m', 'multiple_choice'), ('s', 'single_choice'), ('i', 'integer'), ('e', 'email')], default='s', max_length=1),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey')),
            ],
        ),
    ]
